### ISSUE TITLE
Build multiple JavaScript files

### ISSUE THREAD

**Issue by searls** [linemanjs/lineman#165]
For lots of reasons, Lineman pushes you very hard to deploy a single concat'd and minified JavaScript file for your entire application, but sometimes there's good reasons to break things up, especially when your app gets large and you've got a big chunk of code that's only ever going to be used by a small proportion of your audience.

How I'd like to address this is to give users a configuration feature for building  additional JavaScript like this:

``` coffeescript
extra:
  js: 
    foo:
       src: ["app/extra/js/foo/**/*"]
       dest: "js/foo.js"
```

In the above case, all of the current JS-related tasks would run again for the files under `app/extra/js/foo` and build to `dist/js/foo.js`. 

We could generalize this quite a bit. For example, if no custom globs are necessary, a user could just start adding JS/Coffee files  to `app/extra/js/bar` and without configuring anything will receive `dist/js/bar.js` as a build of that JS.

This would present a little bit of a challenge for us as implementers, because we'd have to generalize all of the stuff that currently happens to stuff under `app/js` into an easy-to-repeat formula. What's more, if someone wants to switch a task out (say concat-sourcemap instead of concat), they probably want it to apply to all of their JS-related tasks. So therefore I'd propose that we introduce a new grunt "meta task" for the JS stuff that would receive as options the tasks that should run for JS stuffs, a la:

``` coffee
meta:
  commonJs:
    options:
      tasks: ["coffee", "jshint", "handlebars", "jst", "concat"]
  distJs: 
    options:
      tasks: ["uglify"]

appTasks:
  common: ["less", "meta:commonJs",  "images:dev", "webfonts:dev", "pages:dev"]
  dev: ["server", "watch"]
  dist: ["meta:distJs", "cssmin", "images:dist", "webfonts:dist", "pages:dist"]
```

Of course, the above would introduce no shortage of other small points of back-compat panic and make the JS build even less obvious.

Feedback on this approach?

This enhancement if implemented will address many of the needs outlined by #150

**Comment by davemo** [comment]
https://github.com/linemanjs/lineman-vendor-split does this now :)
