### ISSUE TITLE
Moonshot: Inter-process messaging

### ISSUE THREAD

**Issue by searls** [linemanjs/lineman#176]
My work in #175 is requiring a lot of explicit waits while `lineman run` does its thing. It'd be much nicer if (as a child process) I could get called back whenever the watch task finished executing stuff.

**Comment by davemo** [comment]
Something like this was done in some code that lives in a comment in #185 :package: 

https://github.com/linemanjs/lineman/issues/185#issuecomment-32305104

`target.tasks.push("emit:compile_end")`

`grunt.event.emit('compilationTasks', Object.keys(changes).length)`
