### ISSUE TITLE
Plugin API should be expanded to define & override CLI actions

### ISSUE THREAD

**Issue by searls** [linemanjs/lineman#208]
Right now the lineman CLI is basically all governed by a single file with no real clear rhyme or reason. We should factor it out into part of the plugin discovery system and allow third-party plugins to define (and extend) existing lineman CLI actions.

Would require some internal design gymnastics, because it'd require us to separate plugin discovery from the current configuration-munging (not a bad idea anyway), but would be great for plugins who need to add new behavior (like `lineman deploy` or `lineman runTestsInABrowser`)

**Comment by davemo** [comment]
Thoughts on if this is still relevant @searls?

**Comment by searls** [comment]
Eh, I think this is really just sugar 99% of the time for what would as well be `lineman grunt new-thing`. I don't think it's that necessary
