### ISSUE TITLE
lineman plugins to make use of npm run-script

### ISSUE THREAD

**Issue by jasonkarns** [linemanjs/lineman#217]
We currently have a set of plugins that expect a preconfigured directory structure. The directory setup is provided by the various linamen-*-template repos, but I think this can be improved.

What if the directory structure setup could be done via a plugin's script? So, for example, the lineman-angular plugin could have a `configure` or `setup` script in its `package.json`. It could create (if they don't already exist) the `js/{controllers,directives,resources,services}` directories and `js/{app,router}.js` files.

It would be executed as `npm run-script lineman-angular configure`.

Thoughts?

**Comment by davemo** [comment]
@jasonkarns has this been sat on enough? is it still relevant? needs more sitting? :D

**Comment by jasonkarns** [comment]
npm run-scripts no longer support invoking a script of a dependency as they once did.
