### ISSUE TITLE
Can we proxy socket.io?

### ISSUE THREAD

**Issue by Foxandxss** [linemanjs/lineman#239]
Hello my friends. I started to play today with socket.io.

I have a chat app on a node app running at port 3000 and a Lineman app (using Angular).

I can see that `/socket.io/socket.io.js` is there but I can't use it. I get:

`WebSocket connection to 'ws://localhost:8000/socket.io/1/websocket/B5jbFD3abblGRTyKRjYz' failed: Connection closed before receiving a handshake response `

I read that is a problem of using a proxy.

Is there any solution or workaround for us? :)

**Comment by jayharris** [comment]
Is this done, or is this just being closed as included in #261?

**Comment by davemo** [comment]
Just closed as I felt the discussion duplicated what was in #261
