### ISSUE TITLE
Can we start using Broccoli to manage builds?

### ISSUE THREAD

**Issue by searls** [linemanjs/lineman#274]
After meeting @joliss and hearing about her aspirations for Broccoli as a library for building build tools (e.g. not necessarily the end-all/be-all CLI, but rather responsible for coordinating the tasks that are common to anyone building static assets, I've been chewing on whether it makes sense for us to make an effort to migrate to Broccoli

Advantages I'd look for:
* Access to much faster tasks (because they model the build tree, they can safely &  aggressively cache). The Coffee filter is a really impressive example of the kind of performance Broccoli's "filter" (e.g. 1:1 file) tasks can achieve.
* Supports invoking grunt tasks. I'm sure you lose a lot of project-awareness stuff when you invoke grunt tasks from Broccoli, but it gives me hope that we could introduce it and then incrementally replace slower grunt tasks when faster Broccoli ones are available, continuing to support both going forward.

Hopes: 
* The fact is that Lineman does *extremely little* to add behavior on top of Grunt as if to be a "build tool", we really just gather a list of stringy task names and then kick grunt off. See [this hunk](https://github.com/linemanjs/lineman/blob/master/lib/cli/main.coffee#L32-L35). That gives me hope that we'll have a very easy point to kick Broccoli off.

Cautions:
* It sounds like a lot of work, but I don't know yet.
* I'm always afraid of making any backwards-compatible-breaking changes to Lineman. I'm unsure how to deal with exposing an API for ordering tasks & targets as it is, and now it'd be complicated by whether folks mean "the grunt coffee" task or the "broccoli coffee task"; meting out differences in their configuration objects would also be tricky.

@joliss if you have the time, would you mind scanning this issue for any red flags? I haven't even pulled down broccoli yet to start using it, so it's very possible I'm describing the impossible (or unrecommended).

**Comment by davemo** [comment]
Closing this as https://github.com/cabbagejs/cabbage is a thing.
