### ISSUE TITLE
Webfonts only from vendor by default

### ISSUE THREAD

**Issue by TravisTheTechie** [linemanjs/lineman#278]
Per some issues getting started with lineman-blog (https://github.com/linemanjs/lineman-blog-template/issues/7) I saw webfonts are only served from vendor by default. I might be out of the norm, but it's common for me to generate all the icons as a font, because vectors and retinas :eyes:.

**Comment by davemo** [comment]
What did you end up doing to solve this @TravisTheTechie? Do you still think this would be worthwhile to change in Lineman core?

**Comment by TravisTheTechie** [comment]
I just changed the config so that it copied from my app assets as well. I feel like including that config in core would make sense, but isn't required.

**Comment by davemo** [comment]
Thanks! :)
