### ISSUE TITLE
Grunt Config Help: Question: how can I limit expansion of subdirectories individual views in /pages

### ISSUE THREAD

**Issue by raibutera** [linemanjs/lineman#282]
I'm pretty bad at understanding how lineman's grunt tasks work, but at the moment I have a lot of html files in `app/pages` and I would like to organise them into `app/templates/` and other subdirectories for related views.

However, when I do so pages:dev simply puts them all into the root of `/generated/` - how do I modify it so that files in subdirectories in app/pages/ get placed into a corresponding subdirectory in `generated/`?

**Comment by davemo** [comment]
If the files are purely static HTML and not leveraged by any pre-processing task within Lineman I would just put them in `app/static`. If you need to customize something like `grunt-angular-templates` you can always override the way `lineman-angular` configures that plugin inside of `config/application.coffee`.
