### ISSUE TITLE
How to use forever with linemanjs

### ISSUE THREAD

**Issue by swapneshk** [linemanjs/lineman#298]
How  can I forever start my application in production. I tried -

> forever start lineman.js in config folder but it is not working.

**Comment by davemo** [comment]
Hi @swapneshk; Lineman is intended to be used to run your application in development mode with `lineman run` and build static assets for deployment into a web server with `lineman build`. I'm not familiar with `forever` but I imagine what you are trying to do probably requires something like `forever lineman run` at the project root.
