### ISSUE TITLE
troubleshooting grunt task for lineman plugin development

### ISSUE THREAD

**Issue by dcunited001** [linemanjs/lineman#314]
I'm trying to write a lineman-vulcanize plugin, which uses the grunt-vulcanize task.  i've pretty much gotten the lineman plugin wired up correctly, but i cannot for the life of me determine what input the grunt-vulcanize task is getting.

i can't do a `grunt.log.warn()` or `grunt.log.writeln()` or anything.  i'm running the task with `lineman grunt -v vulcanize` and it runs, but nothing happens.  I'm using `npm link` on both lineman-vulcanize and grunt-vulcanize to try to see what input grunt-vulcanize is getting.  what's the best way to debug and troubleshoot here?  I know the problem is something simple.  I've tried looking at `lineman config` and everything looks correct.  the only thing i can successfully do is crash grunt while it's running the task by adding a syntax error.

**Comment by davemo** [comment]
Hi @dcunited001, sorry I failed to follow up with you on this. Did you end up sorting it out? If not, my offer is still open to pair on zoom.us; availability for me is limited to weekdays from 9am - 5pm EST, but if that works feel free to email me and setup a time :)
