### ISSUE TITLE
Lineman returns code 143

### ISSUE THREAD

**Issue by tandrewnichols** [linemanjs/lineman#321]
Seems like every time we save a file being watched and our server restarts, we get this in the spawn output (Note the "error" reported by "watch" the second time):

```
Running "watch" task
Waiting...
setting static path to  /Users/AndrewNichols/code/anichols/manta/manta-frontend/client/generated/
running static build:  { version: 'b8a2d2d' }
CDN hosts:  []
Express server listening: app port (3030) worker id (undefined) pid (32243)
OK
>> File "../server/lib/utils.js" renamed.

Running "writeStaticBuildFile" task
Adding static build file to `/Users/AndrewNichols/code/anichols/manta/manta-frontend/client/generated` with values: {"version":"b8a2d2d"}
Adding static build file to `/Users/AndrewNichols/code/anichols/manta/manta-frontend/client/dist` with values: {"version":"b8a2d2d"}

Running "manta_server" task
Restarting the express server

Running "watch" task
Waiting...
[Error] { stdout: '', stderr: '', code: 143, toString: [Function] } 143
setting static path to  /Users/AndrewNichols/code/anichols/manta/manta-frontend/client/generated/
running static build:  { version: 'b8a2d2d' }
CDN hosts:  []
Express server listening: app port (3030) worker id (undefined) pid (32257)
```

This isn't a problem most of the time. But we've noticed that sometimes (and who knows why), this same error/code (143) is reported when travis runs . . . which it interprets as a test failure, even if all the tests actually passed.

We're not using the most recent lineman, but I pulled down the most recent and verified that it still happens there. This _may_ be a lineman issue, or it may just be an issue with our server task, though I don't see anything specifically wrong with the task, and a similar task (and I mean, nearly identical) that I run in another project, but directly with grunt, doesn't have this problem.

Any insight?

**Comment by davemo** [comment]
Hi @tandrewnichols, is this still a problem for you or did you manage to find a solution?

**Comment by tandrewnichols** [comment]
Yeah, we found a solution, although we don't use lineman anymore, so I don't recall what it was.
