### ISSUE TITLE
Why does 'npm install lineman-less' say I am missing a file at '/Users/peteheard/app/css/main.less'?

### ISSUE THREAD

**Issue by peterheard01** [linemanjs/lineman#330]
I am totally flummoxed by this. 

I have re-installed node.
I have reinstalled lineman globally.
I have cleared the npm cache.

But when I download the lineman-angular-template and run....

npm install or npm install lineman-less

I get this error....

![screenshot 2014-11-01 13 13 45](https://cloud.githubusercontent.com/assets/3805883/4871812/5347b666-61c9-11e4-9084-a0a906da9bdc.png)

Why on earth would installing lineman-less want me to have a less file in my own user directory? Totally can't get my head around it! Help! 

:-)

**Comment by jayharris** [comment]
@peterheard01 I know this is an old issue, but do you happen have a `package.json` in `Users/peteheard`?

**Comment by jasonkarns** [comment]
sounds like this is likely: jasonkarns/node-find-root-package#1
