### ISSUE TITLE
Will lineman allow me to hook a command line direct instead of through grunt?

### ISSUE THREAD

**Issue by peterheard01** [linemanjs/lineman#333]
Hi, I tried for an hour or two to get this working.

I have a task which is invoked by...

lineman grunt spec-int

And it all works lovely. But I want to be able to just do...

lineman spec-int

Is there an extensibility point here because when I wrote a module it didn't work :-(

The other thing is I would like to include my new command as part of lineman spec-ci command is this possible?

**Comment by felippenardi** [comment]
This doesn't seem a problem — agree with searls that it is just cosmetics.

I'm interesting though in understanding how to create custom tasks on lineman environment, can you show it @peterheard01 ?

**Comment by davemo** [comment]
@felippenardi you can just add tasks to the `tasks` folder within a lineman project, they will be automatically loaded by grunt and can be configured within `config/application.{js,coffee}`, here's an example from something I'm working on:

https://github.com/davemo/practical-angularjs/blob/bceb5457b124af97e4d353b18ce46954aabb94d9/codemash/start/tasks/preload_angular_data.coffee

**Comment by felippenardi** [comment]
Super! Thanks @davemo :)

**Comment by peterheard01** [comment]
http://www.urlhelper.co.uk/create-task-lineman-js/ <http://www.urlhelper.co.uk/create-task-lineman-js/>

:-)

**Comment by felippenardi** [comment]
@peterheard01 wow! You didn't need to create a blog entire post for me!
just kidding, thanks a lot :)
