### ISSUE TITLE
generated/js/vendor.js and generated/js/app.js

### ISSUE THREAD

**Issue by peterbe** [linemanjs/lineman#334]
At the moment, `lineman run` generates `generated/js/app.js` which is nice. It contains all the vendor/*.js and all the app/**/*.js into one massive file. 

I would like to split that up so it generated two files instead (so my `index.us` would have two `<script>` tags). 
How is this possible?

My goal is to be able to limit coverage analysis to exclude things like `generated/js/vendor.js` and I suspect that when going into production my `dist/js/vendor.js` will less likely change over time but `dist/js/app.js` will more frequently. 

Also, I think the browser could benefit from downloading and parsing two files simultaneously.

**Comment by davemo** [comment]
Hey @peterbe and @jayharris, I just released `lineman-vendor-split` which should help with this. Try it out and let me know if it works for you :) https://github.com/linemanjs/lineman-vendor-split
