### ISSUE TITLE
Why template file is .us?

### ISSUE THREAD

**Issue by felippenardi** [linemanjs/lineman#338]
Hello,

I couldn't find not he Docs any information on what this `.us` extension is. What capabilities does it gives to the HTML? Otherwise, why not just `.html`?

**Comment by searls** [comment]
It's an underscore template. You can use underscore interpolation to evaluate and interpolate JavaScript with `<% %>`  `<%= %>`, respectively. 


You can also discard this feature and rename it to .html

**Comment by felippenardi** [comment]
Thanks :)
