### ISSUE TITLE
How lineman is supposed to be updated?

### ISSUE THREAD

**Issue by felippenardi** [linemanjs/lineman#339]
Hello guys,

I'm using the lineman-angular-template. According to its instructions, I should clone and then customize it to my needs.

My question is: how does I update lineman later? I can't merge the lineman-angular-template becauses it cames with the templates itself.

**Comment by davemo** [comment]
The lineman-angular-template is really intended as a learning tool that sets you up with examples of testing, push-state configuration, authentication and route control and some simple view management. I've found it much easier to get started on a new Angular project by using `lineman new` and then installing `lineman-angular` with `npm i lineman-angular --save-dev`.

That way, you don't inherit all of the examples from lineman-angular-template which should make updating lineman or lineman-angular a little easier :)

**Comment by felippenardi** [comment]
Then lineman-angular would become a npm dependency, that is good. And how about the lineman itself?

How can I update what was generated by `lineman new`?

**Comment by searls** [comment]
Lineman runs globally if it's not present locally in node_modules. If it's installed locally (e.g. you specify the version you would like in your package json and run `npm install`), then that version wins and the project runs at that version.
