### ISSUE TITLE
How to `lineman build` with no uglify?

### ISSUE THREAD

**Issue by felippenardi** [linemanjs/lineman#340]
Hello,

I want to build with no minification. How does I ignore uglify on `lineman build`?

**Comment by jasonkarns** [comment]
See 'Removing Tasks' on the lineman site: http://www.linemanjs.com/#removing-tasks

The task you want is `uglify` and is part of the `dist` phase (`dev` is for `lineman run`, `dist` is for `lineman build` and `common` is for both).

**Comment by felippenardi** [comment]
@jasonkarns Thank you! There is another problem now
I added this snippet to `config/application.js`:

```javascript
 removeTasks: {
    dist: ["uglify"]
  }
```

It successfully removed uglify, but it is not building the `/js` folder anymore.

What is the task that builds the JS, just not minified?

**Comment by felippenardi** [comment]
Just solved this issue by replacing the previous snippet with:

```javascript
uglify: {
  options :
    {
      beautify: true
    }
}
```

**Comment by searls** [comment]
Glad you got to this before I did. I also would not remove uglify, I'd have gone your route (since you'd have to add a copy task after concat to replace the need to move from generated into dist
