### ISSUE TITLE
Cannot use newer JSHint option: `latedef: "nofunc"`

### ISSUE THREAD

**Issue by mark-rushakoff** [linemanjs/lineman#342]
I'm trying to use JSHint's `latedef: "nofunc"` option, but it isn't being respected in Lineman. I believe this is because Lineman [includes grunt-contrib-jshint 0.6.4](https://github.com/linemanjs/lineman/blob/1afc3127fef653fcc9938ddc2e76f21043ef22a5/package.json#L37) and grunt-contrib-jshint is [currently on version 0.11.0](https://github.com/gruntjs/grunt-contrib-jshint/commit/a3d1a5b6240e8b77ca6d3b20d2ff77bdb83b2253). `latedef: "nofunc" is a relatively newer option, but I'm not yet experienced enough with Node to know how to verify this fix myself.

**Comment by davemo** [comment]
Hi @mark-rushakoff, please remove and install the latest release of Lineman. I pushed an update and revision `0.34.4` fixes this as well as upgrades grunt to `0.4.5` in the process

**Comment by mark-rushakoff** [comment]
Thanks for the really quick fix! Upgrading JSHint allowed me to use the new option that I wanted. You all are doing so great on response time to GitHub issues that [I had to tweet about it](https://twitter.com/rushakoff/status/560153518355386368).
