### ISSUE TITLE
js2coffee v2.0.0 is out

### ISSUE THREAD

**Issue by rstacruz** [linemanjs/lineman#345]
lineman depends on js2coffee. Here are some notes on migrating to 2.x: https://github.com/js2coffee/js2coffee/blob/master/notes/Migration_guide.md

**Comment by searls** [comment]
I'm not sure what we'd gain by upgrading. Right now our usage is really minor (just archetype generation for `--coffee`)

**Comment by rstacruz** [comment]
just thought i'd let you guys know. If anyone reports any issues on doing `npm install` with js2coffee being to blame though, you might consider bumping up the requirement to `^2` :) some folks reported problems with that on js2coffee 0.3.x.

**Comment by searls** [comment]
Will do. Feel free to reopen
