### ISSUE TITLE
Cannot install lineman on win8.1. Several errors

### ISSUE THREAD

**Issue by kamilrak** [linemanjs/lineman#348]
I have a problem installing lineman on win 8.1.
Once I've python 2.7.9 installed on my pc I got:
 - MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available too
ls versions are "4.0".

I've read on stackoverflow I should install visual studio (is it correct?), but the idea to install 8GB App in order to get rid off error sound funny... Anyway I did this and got:
- C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(882): fatal error
 C1083: Cannot open include file: 'qos.h': No such file or directory
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1

and so on. 
Npm -v -> 1.4.28
node -v ->0.10.36

I've tried with insallation of nodejs for both x86 and x64 OS.

**Comment by searls** [comment]
Hi, sorry to hear you're having issues. Unfortunately, none of this gives me a sense of what needs to be done to resolve your issue. I'd be down to debugging and googling as well … :/

**Comment by jayharris** [comment]
This isn't an issue with Lineman, but instead is an issue with your Node configuration.

Many Node modules rely on [addons that need to be compiled](http://nodejs.org/api/addons.html). Web Socket clients and Crypto tools are example addons that are also used within third-party libraries that Lineman depends on. All addons within Node are all compiled with [node-gyp](https://github.com/TooTallNate/node-gyp), which is where your Python installation comes in to play and where your issues are occurring.

I recommend checking out the [node-gyp](https://github.com/TooTallNate/node-gyp) page for more information on its Windows requirements. Also, one of the base libraries that uses `node-gyp` is `ws`. When your configuration is functioning properly, you should be able to successfully run `npm install ws`.
