### ISSUE TITLE
What is the best way to add a http header in the express server response?

### ISSUE THREAD

**Issue by rsbrodie** [linemanjs/lineman#349]
I would like to add an http header in the express server response.  What is the best way to do this in LinemanJS?  Is there an entry that can be made in the config/server.js file?

**Comment by davemo** [comment]
Hi @rsbrodie, you can modify `config/server.js` and leverage any of the express API's to make changes to the `request` and/or `response` objects. Here's an example in a Lineman project where I modify headers to add CSRF token information for Angular:

https://github.com/davemo/practical-angularjs/blob/master/codemash/finish/config/server.js#L19-L36
