### ISSUE TITLE
Error: Cannot find module 'StringScanner'

### ISSUE THREAD

**Issue by itsNikolay** [linemanjs/lineman#359]
```
$ lineman fetch backbone 

module.js:340
    throw err;
          ^
Error: Cannot find module 'StringScanner'
```
Versions:
```
$ lineman --version 
0.36.0
$ nodejs --version 
v0.10.38
$ bower --version 
1.4.0
```

**Comment by searls** [comment]
Unfortunately I'm not able to replicate off a fresh lineman install. Are you on Windows?

**Comment by itsNikolay** [comment]
@searls Ubuntu 14.04
Can I somehow help?

**Comment by searls** [comment]
I would at this point hop into whatever is rowing it and debug. I doubt I have any more familiarity as to the issue than anyone else would.
