### ISSUE TITLE
Totally brokes after changing <%= js %>

### ISSUE THREAD

**Issue by itsNikolay** [linemanjs/lineman#360]
When I change `app/pages/index.us` line
```html
<script type="text/javascript" src="<%= js %>"></script>
```
to
```html
<script type="text/javascript" src="<%= files.js %>"></script>
```
localhost:8000 becomes blank (no styles, no title tag, no script tags)
end ever restarting of lineman do not help

(I build a new app with `lineman new demo --coffee` and did steps above.) 
Before those steps, everything worked well.

**Comment by searls** [comment]
Why would you make this change? Why is this unexpected?

**Comment by itsNikolay** [comment]
@searls I tryed to find a way to not concatenate files. But found that :disappointed:

**Comment by searls** [comment]
Sorry, Lineman is designed to concatenate files. If you don't wish to, you're probably better off with a different tool unless you want to add support to lineman-core with a PR.

**Comment by itsNikolay** [comment]
@searls I will look through the Lineman 
Thanks for the rich answer
