### ISSUE TITLE
How to run unit tests with PhantomJS?

### ISSUE THREAD

**Issue by felippenardi** [linemanjs/lineman#361]
How do I get PhantomJS setup on Lineman for unit tests?

**Comment by searls** [comment]
Running `lineman spec-ci` runs a default lineman project's tests under phantomjs out of the box :smile:

**Comment by felippenardi** [comment]
Thanks @searls ! And is there a way to run it continuously?

**Comment by searls** [comment]
Just set phantomjs as the runnier in your spec.json and it'll run them in development mode with lineman spec.

**Comment by felippenardi** [comment]
@searls Man, seriously, can I pay you a coffee? Thank you so much :)

**Comment by felippenardi** [comment]
@searls You've just saved me at least 30 per day.

**Comment by searls** [comment]
Have fun!
