### ISSUE TITLE
Livereload seems to trigger before other tasks

### ISSUE THREAD

**Issue by trazek** [linemanjs/lineman#365]
It seems when livereload is configured, it gets triggered before other grunt tasks. Is there a way to defer livereload until after a set of tasks have finished?

**Comment by searls** [comment]
Well, that certainly doesn't sound good. Can you take a look at https://github.com/testdouble/grunt-watch-nospawn and identify what's up?

**Comment by william-fuller** [comment]
Having the same issue. Just uncommented out Live Reload and it fires before Scss has finished compiling.
