### ISSUE TITLE
lilneman spec-ci not working

### ISSUE THREAD

**Issue by dematic-rodrigo-silveira** [linemanjs/lineman#366]
I have been using lineman / lineman-angular / test'em and I love it. Following is an unexpected error with _lineman spec-ci_:

# Steps to reproduce
1. run _lineman spec_ and observe that all is well. See screen shot 
![screen shot 2015-06-08 at 09 15 01](https://cloud.githubusercontent.com/assets/10092790/8039532/50567b34-0dbf-11e5-8864-425c682dadf0.png)
1. Cause a test to fail. See screen shot from running _lineman spec_
![screen shot 2015-06-08 at 09 14 43](https://cloud.githubusercontent.com/assets/10092790/8039545/6a5ac918-0dbf-11e5-8de6-bfdb35455204.png)
1. Run _lineman spec-ci_

# Observed Behavior
1. It reports that no tests were run and that all tests passed, see screen shot
![screen shot 2015-06-08 at 09 20 43](https://cloud.githubusercontent.com/assets/10092790/8039580/ad43e5f2-0dbf-11e5-8f75-813a032f5189.png)

# Expected Behavior
1. Execution of lineman spec-ci indicates that 78 tests were executed, and one test failed.

Thanks in advance for any insights you might have on this.

Regards
Rodrigo

**Comment by StephenTurley** [comment]
I just noticed this happening in my local builds as well.

**Comment by StephenTurley** [comment]
I just figured out what was causing the problem for me. spec-ci requires phantomjs. phantomjs has some added dependencies that were not installed on my system (Fedora 21). Try doing a "sudo npm install -g phantomjs". This should pull in all the dependencies that you need.

**Comment by dematic-rodrigo-silveira** [comment]
@StephenTurley Just noticed your comment, thanks! I'll try and let you know.
