### ISSUE TITLE
Adding Bootstrap SaaS version

### ISSUE THREAD

**Issue by harshamv** [linemanjs/lineman#367]
I am new to Lineman and i am finding it very hard to understand and get started. The Documentation is not good enought for a beginner like me. 

I am trying to add Bootstrap SaaS version into my project but the fetcher is adding the css versions of it. 
When i add them manually into the vendors folder how can i include them into my main.scss file?

**Comment by searls** [comment]
If you want to include the Sass version of bootstrap, you'll need to
download it and drop it into vendor/css. Then you can @import it from your
app/css/main.sass.
