### ISSUE TITLE
How can I move the my-lineman-app/node_modules folder to a folder outside my-lineman-app

### ISSUE THREAD

**Issue by dematic-rodrigo-silveira** [linemanjs/lineman#371]
Hi - I'm writing this in hopes of saving the the blood, toil, sweat, and tears of figuring it out in case someone else has done it already. I have figured out what to do about the *vendor* files.

Our company police establishes that only our own source code are to be kept in our repositories. All the files in *my-lineman-app/node_modules*  and *vendor* are not our source code and must be moved elsewhere.

Thanks in advance for your help.

Regards

**Comment by dematic-rodrigo-silveira** [comment]
I just realized that the ,gitignore file is missing from my *my-lineman-app* folder.

**Comment by dematic-rodrigo-silveira** [comment]
I thought I found the problem when I added *my-lineman-app/node_modules* to *.gitignore*. Close, but no cigar. I need these modules in the build server and I would like to avoid having to *npm install* every build. My next step is to install them globally in the build server and see what happens. In the mean time, any insights would be welcome.

**Comment by dematic-rodrigo-silveira** [comment]
I found the answer, the [npm registry](https://docs.npmjs.com/misc/registry) enables me to set up a local registry.

How about this ... I created the issue ... then banged my head around and ended up finding a way to deal with it before anyone added any comments.

Well, sorry for polluting the roster, although this might be useful to someone else.

**Comment by searls** [comment]
Thanks for documenting what you did @dematic-rodrigo-silveira.
