### ISSUE TITLE
lineman run fails after using grunt-exec

### ISSUE THREAD

**Issue by dematic-rodrigo-silveira** [linemanjs/lineman#376]
#### DESCRIPTION
As it will be shown below, all is well until a task that uses *grunt-exec* is executed; the same happened with *shelljs*. Once a command shell is used to issue an external command, *lineman* gets into a strange state preventing it form performing its basic work.

#### STEPS TO REPRODUCE

 * Ensure I'm using *lineman v-0.36.4*
 * Install *grunt-exec* using, *npm install grunt-exec --save-dev*
 * Update *application.js* to use the *DLABS fetcher-recipe repository*
```javascript
module.exports = function(lineman) {
		... removed for brevity
        fetcher: {
            recipeRepo: "https://github.com/Dematiclabs/fetcher-recipes"
        }
    };
};
```
 * Define a task, *dl-fetch*, to load ALL my libraries (right now only two are defined)
```javascript
module.exports = function(grunt) {
   grunt.initConfig({
      exec: {
         'angular': 'lineman fetch "angular"',
         'angular-bootstrap': 'lineman fetch "angular-bootstrap"'
      }
   });
   grunt.loadNpmTasks('grunt-exec');
   grunt.registerTask('dl-fetch', ['exec']);
};
```
 * Run *lineman run*, observe that it works well, as indicated by the hereafter included logs:
```bash
$ lineman run
Running "common" task

Running "ngtemplates:app" (ngtemplates) task
File generated/angular/template-cache.js created.

... omitted for brevity

Running "watch" task
Waiting...
```        
 * Run the task to load libraries, it works well

```bash
$ lineman grunt dl-fetch
Running "exec:angular" (exec) task
Fetching recipes from 'https://github.com/Dematiclabs/fetcher-recipes'...
Downloading 'http://code.angularjs.org/1.4.5/angular.js'...
        
... omitted for brevity
Successfully installed 'angular-bootstrap'.
 ```

#### OBSERVED BEHAVIOR

 * Run 'lineman run', observe that it fails, as indicatec by the hereafer included logs:
```bash
$ lineman run
Running "common" task

>> No "ngtemplates" targets found.
Warning: Task "ngtemplates" failed. Used --force, continuing.
        
... omitted for brevity
        
Running "watch" task
Verifying property watch exists in config...ERROR
>> Unable to process task.
Warning: Required config property "watch" missing. Used --force, continuing.

Done, but with warnings.
```

#### EXPECTED BEHAVIOR
The *lineman run*, and all other lineman functionality, should work after running *lineman grunt dl-fetch*

**Comment by dematic-rodrigo-silveira** [comment]
#### SOLUTION
After debugging the problem, I learned that the undesired symptoms are only when the *dl-fetcher.js* file is present! The root-cause, it is the following code snippet in  *dl-fetcher.js*:

```javascript
   grunt.initConfig({
        exec: {
            'angular': 'lineman fetch "angular"',
            'angular-bootstrap': 'lineman fetch "angular-bootstrap"'
        }
    });
```

It totally resets the whole lineman configuration! OUCH! The solution was to declare the exec object in applications.js:
```javascript
       . . . 
        exec: {
            'angular': 'lineman fetch "angular"',
            'angular-bootstrap': 'lineman fetch "angular-bootstrap"',
            'underscore': 'lineman fetch "underscore"'
        },
        . . . 
```

This was an excellent exercise, I know fully understand how to write grunt tasks for lineman!

Sorry for taking up space here. On the other hand, writing this helped me figure out the solution. I also hope that folks who read it might learn from it.

**Comment by searls** [comment]
Hey we don't mind you working in the open. It might help someone else in
the future. Glad it worked out.
