### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by Power-Inside** [linemanjs/lineman#379]
Lineman reports incorrect version?

When I check for the version by running `lineman version` it says 0.36.0, but when I do `npm -g list lineman` I get 
```
/usr/lib
`-- lineman@0.36.4 
```

**Comment by searls** [comment]
The lineman CLI when installed glovally, will always delegate to the locally installed lineman (if it exists). In this case you have 0.36.4 globally and very likely 0.36.0 installed in your app's node_modules directory. 

Reopen if I'm wrong though

**Comment by Power-Inside** [comment]
Oh, yes my bad.. I found a symlinked executable in `/usr/local/bin` that pointed to the old one in `/usr/local/lib/node_modules/lineman/...` and I just needed my shell to use the one from `/usr/bin/` instead. 
I deleted `/usr/local/bin/lineman` and it's all fine now.

The culprit was probably the NODE_PATH env variable which was changed (I'm not sure what led to this.. must be some node/npm upgrade)

Sorry for the false alarm!
