### ISSUE TITLE
Heroku support

### ISSUE THREAD

**Issue by peterheard01** [linemanjs/lineman#384]
Hey Chaps,

Did you ever get this working with the new version of Heroku? If not did you want some help?

Someone recommended I get involved with open source more so I love lineman and would like to help keep it up to date. Perhaps do a gulp version?

I have no idea how much work this is by the way so just let me know where the project is at the moment and if you are looking for collaborators....

Pete

**Comment by davemo** [comment]
Hi @peterheard01, we have pretty good heroku support with the latest version of the Cedar stack! We've got this documented here: http://linemanjs.com/#heroku-deployment

If you're looking for a good example, check this out: https://github.com/hone/lineman.js-on-Heroku

**Comment by peterheard01** [comment]
So it's working on Cedar 14? Only I was using lineman then I started getting problems and Justin said there were issues and would need to be fixed. I will start using again if it's now working...

**Comment by searls** [comment]
Yep, we recommend using @hone's new static buildpack. Check out
https://github.com/testdouble/double-takes as an example.

**Comment by searls** [comment]
Here is @hone's example repo: https://github.com/hone/lineman.js-on-Heroku

**Comment by peterheard01** [comment]
Ok great going to start using that then. Are there any on going extensions for Lineman? I have been recommended to start doing more open source. I find a lot of it boring but I like lineman so would like to help a little.

**Comment by searls** [comment]
Hey Pete, most of the extensions are what we need. I know the
lineman-browserify plugin doesn't really work effectively, so you might
want to take a look at that.
