### ISSUE TITLE
Time-Grunt Integration

### ISSUE THREAD

**Issue by dumbguy5689** [linemanjs/lineman#392]
It would be great to have https://github.com/sindresorhus/time-grunt layered in (or somthing that tracks the time of all the grunt tasks).  I find as the day goes on things can get quite slow so I'm using this to try and troubleshoot the bottleneck. 

I was able to add it in via manually changing the Gruntfile but I would assume there is a more graceful way:

````
/*global module:false*/
var timer = require("grunt-timer");

module.exports = function (grunt) {
  timer.init(grunt, { friendlyTime: true });
  require('./config/lineman').config.grunt.run(grunt);
};
````

**Comment by searls** [comment]
If this worked for you I'd just roll with it. I don't think we'd pull this into the core lineman project since it's only necessary when profiling performance.

**Comment by dumbguy5689** [comment]
@searls Is there a more elegant way to integrate it (without having to go into the gruntifle directly?)? Currently for example the "total" doesn't display until the "Watch" task is finished (basically when a change is detected).

**Comment by searls** [comment]
Sorry, but I'm not familiar with the module or how it works.

**Comment by dumbguy5689** [comment]
@searls Thanks, sorry for the basic questions, still trying to figure out how to properly incorporate grunt through the lineman configs, etc.
