### ISSUE TITLE
linemanjs.com links to casino site

### ISSUE THREAD

**Issue by RCVarley** [linemanjs/lineman#395]
The link in the documentation to linemanjs.com no longer links to the official documentation.

**Comment by searls** [comment]
🤦‍♂ thanks. I'll get that fixed

**Comment by searls** [comment]
After fighting with lineman-docs for two hours to get it to build I gave up and just pointed the README to the repo's markdown files ☹️ 

Anyway thanks so much for pointing this dead link out!

Fixed in 21bb1bac555665983f63d49769a6b3712113faf2
