### ISSUE TITLE
Make `lineman new` even better

### ISSUE THREAD

**Issue by searls** [linemanjs/lineman#58]
As of 0.5.0, `lineman new` doesn't locally re-install lineman locally. This is a great start to making lineman easier to start using.

One side effect is that running `npm install` at any point in the app's life will have the incidental effect of installing & freezing your lineman install, which may not be intentional. Maybe all the user wants to do is add a new dependency.

Me & @davemo chatted and I think the right way out is to do this:

* Remove the lineman dependency from the archetype's package.json file
* Add a `.lineman-version` file to the archetype that prints the lineman version used to create the project.
* Add a `lineman freeze` command that optionally takes a version argument (but defaults to reading that `.lineman-version` file) and adds lineman as a locked dependency to the package.json and then performs an npm install.

The reason for the extra effort here:

Simply removing the dependency and leaving everything global would be fine at first, but if a global lineman upgrade eventually broke everything, or if new team members weren't able to get up and running, then there'd be no record of what version of lineman for which things *did* work. Storing that would be a good idea.

Concerns:

This would probably require that we change the heroku buildpack to be a good deal smarter.

**Comment by davemo** [comment]
I'm inclined to close this as I feel like the upgrade path for a lineman app is pretty infrequent that developing this feature is probably more work than just going through the pain of updating the few things that have changed when migrating an old lineman project to a new version.
