### ISSUE TITLE
Select different vendor files dev/prod

### ISSUE THREAD

**Issue by brandonparsons** [linemanjs/lineman#91]
Hi there!

I've just started trying out lineman - seems like it could be useful!

I'm attempting to use it for Ember development.  As you may know, Ember provides a development JS file with a number of verbose warnings etc. that are great for development, and then a different variation of the file for production (cleaner, not verbose).

How can I re-jig the lineman / grunt tasks to pick up a different file from the vendor directory in `dev` and `build`?

Thanks!

**Comment by davemo** [comment]
After speaking with @searls on this I think it's probably best that we relinquish the ember-intelligence crown and point future users visiting this thread to use [ember-cli](https://github.com/ember-cli/ember-cli) for their ember app needs :)
